- name: Install uwsgi
  ansible.builtin.apt:
    name:
    - uwsgi
    - uwsgi-plugin-python3
    state: present
    
- name: Start and enable uwsgi service
  ansible.builtin.service:
    name: uwsgi
    state: started
    enabled: yes
    
- name: Add uwsgi configuration for agama
  ansible.builtin.template:
    src: ../templates/agama.ini
    dest: /etc/uwsgi/apps-enabled/agama.ini
  notify:
  - Restart uwsgi

