- name: Install uwsgi
  apt:
    pkg: 
    - uwsgi
    - uwsgi-plugin-python3
    state: present
    update_cache: yes
    
- name: Start and enable uwsgi service
  ansible.builtin.service:
    name: uwsgi
    state: started
    enabled: yes
    
- name: Add uwsgi configuration for agama
  ansible.builtin.copy:
    src: ../files/agama.ini
    dest: /etc/uwsgi/apps-enabled/agama.ini
  notify:
  - Restart uwsgi

