{
 "title": "Dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "InfluxDB",
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "influxdb_exporter_stats_query_success",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "MySQL",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 2, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "mysql_up", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Bind9",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 5, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "bind_up", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Keepalived",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "keepalived_up", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "InfluxDB Write Rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(influxdb_write_write_ok[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "A queries / minute",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 0 },
   "targets": [
    {
     "expr": "rate(bind_resolver_queries_total{type=\"A\"}[1m])*100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Haproxy",
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "haproxy_up{instance=\"vm1:9101\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Haproxy backend 1",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 2, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "haproxy_server_up{instance=\"vm1:9101\"}",
     "legendFormat": "{{server}}"
    }
   ]
  },
  {
   "title": "VRRP Status 1",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 7, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "keepalived_vrrp_state{instance=\"vm1:9165\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CPU load",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 6 },
   "targets": [
    {
     "expr": "100 - (avg by (instance) (irate(node_cpu_seconds_total{job=\"linux\",mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Haproxy",
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 0, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "haproxy_up{instance=\"vm2:9101\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Haproxy backend 2",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 2, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "haproxy_server_up{instance=\"vm2:9101\"}",
     "legendFormat": "{{server}}"
    }
   ]
  },
  {
   "title": "VRRP Status 2",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 7, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "keepalived_vrrp_state{instance=\"vm2:9165\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Memory Usage (In MB)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 12 },
   "targets": [
    {
     "expr": "(node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / 1000000",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Nginx",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "nginx_up", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Nginx requests / minute",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 4, "y": 18 },
   "targets": [
    {
     "expr": "rate(nginx_http_requests_total[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Pinger",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 18 },
   "targets": [
    {
     "alias": "[[tag_dst]]",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "dst" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "latency",
     "select": [
      [
       { "params": [ "rtt" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "MySQL Select commands / minute",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 18 },
   "targets": [
    {
     "expr": "rate(mysql_global_status_commands_total{command=\"select\"}[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}