{
 "title": "MySQL",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "type": "stat",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "mysql_up", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "MySQL",
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "mysql_up" }
   ]
  },
  {
   "title": "MySQL Server Id",
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mysql_global_variables_server_id"
    }
   ]
  },
  {
   "title": "MySQL Server Mode",
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mysql_global_variables_read_only"
    }
   ]
  },
  {
   "title": "MySQL replica IO thread",
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mysql_slave_status_slave_io_running{master_uuid!=''}"
    }
   ]
  },
  {
   "title": "MySQL replica SQL thread",
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mysql_slave_status_slave_sql_running{master_uuid!=''}"
    }
   ]
  },
  {
   "title": "MySQL Select commands / minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "rate(mysql_global_status_commands_total{command=\"select\"}[1m])"
    },
    {
     "expr": "rate(mysql_global_status_commands_total{command=\"update\"}[1m])"
    },
    {
     "expr": "rate(mysql_global_status_commands_total{command=\"show_status\"}[1m])"
    }
   ]
  }
 ]
}