- name: Restart bind9
  ansible.builtin.service:
    name: bind9
    state: restarted

- name: rndc reload
  ansible.builtin.shell:
    cmd: rndc reload
  when: inventory_hostname in groups['dns_servers']