- name: Install MySQL exporter
  ansible.builtin.apt:
    name: prometheus-mysqld-exporter
    state: present

- name: Start and enable mysql exporter service
  ansible.builtin.service:
    name: prometheus-mysqld-exporter
    state: started
    enabled: yes

- name: Create user exporter
  community.mysql.mysql_user:
    name: exporter
    password: "{{mysql_exporter_pass}}"
    priv:
      '*.*': 'PROCESS,REPLICATION CLIENT,SELECT'
    login_unix_socket: /var/run/mysqld/mysqld.sock
  notify:
    - Restart mysql exporter

- name: Create configuration file
  ansible.builtin.template:
    src: ../templates/my.cnf.j2
    dest: /var/lib/prometheus/.my.cnf
  notify:
    - Restart mysql exporter