- name: Install prometheus node exporters
  ansible.builtin.apt:
    name: prometheus-node-exporter
    state: present

- name: Start and enable node exporters service
  ansible.builtin.service:
    name: prometheus-node-exporter
    state: started
    enabled: yes