- name: Install keepalived
  ansible.builtin.apt:
    name: keepalived
    state: present

- name: Start and enable keepalived service
  ansible.builtin.service:
    name: keepalived
    state: started
    enabled: yes

- name: keepalived configuration
  ansible.builtin.template:
    src: ../templates/keepalived.conf
    dest: /etc/keepalived/keepalived.conf
  notify: restart keepalived
