- name: Install prometheus
  ansible.builtin.apt:
    name: prometheus
    state: present

- name: Start and enable prometheus service
  ansible.builtin.service:
    name: prometheus
    state: started
    enabled: yes

- name: Apply configuration changes
  ansible.builtin.template:
    src: ../templates/prometheus.yml.j2
    dest: /etc/prometheus/prometheus.yml
  notify:
    - Restart prometheus

- name: Make Prometheus reachable from outside
  ansible.builtin.template:
    src: ../templates/prometheus.j2
    dest: /etc/default/prometheus
  notify:
    - Restart prometheus