- name: Install nginx exporter
  ansible.builtin.apt:
    name: prometheus-nginx-exporter

- name: Start and enable nginx exporter service
  ansible.builtin.service:
    name: prometheus-nginx-exporter
    state: started
    enabled: yes

- name: Create configuration file
  ansible.builtin.template:
    src: ../templates/exporter.j2
    dest: /etc/nginx/sites-enabled/exporter
  notify:
    - Restart nginx
    - Restart nginx exporter