- name: Fix ssl bug for docker
  ansible.builtin.copy:
    src: ../files/iptables.mangle
    dest: /var/local/iptables.mangle

- name: Restore iptables
  community.general.iptables_state:
    path: /var/local/iptables.mangle
    state: restored
    table: mangle

- name: install docker package
  ansible.builtin.apt:
    name:
      - docker.io
      - python3-docker

- name: Start and enable docker service
  ansible.builtin.service:
    name: docker
    state: started
    enabled: yes

