- name: Install bind9
  ansible.builtin.apt:
    name: bind9
    state: present

- name: Start and enable bind9 service
  ansible.builtin.service:
    name: bind9
    state: started
    enabled: yes

- name: Configure DNS forwarders
  ansible.builtin.template:
    src: ../templates/named.conf.options.j2
    dest: /etc/bind/named.conf.options
  no_log: true
  notify:
  - Restart bind9

- name: Configure DNS master zone
  ansible.builtin.template:
    src: ../templates/db.asdf
    dest: /var/cache/bind/db.asdf
  notify:
    - Restart bind9

- name: Reference master zone
  ansible.builtin.template:
    src: ../templates/named.conf.local.j2
    dest: /etc/bind/named.conf.local
  notify:
  - Restart bind9