---
- name: Update apt cache
  ansible.builtin.apt:
    cache_valid_time: 86400

- name: Pause for 20 sec
  ansible.builtin.pause:
    seconds: 20
  when: "'init' not in ansible_run_tags"

- name: hostname
  hostname:
    name: "{{ inventory_hostname }}"
  diff: yes